openapi: 3.0.0
info:
  title: Easy Guide API
  description: The data source for the Easy Guide mobile app.
  version: 0.0.1

servers:
  - url: http://localhost:3001/api
    description: The development server

paths:
  /disabilities:
    get:
      summary: Returns all disability types and subitems
      tags:
        - Disability
      responses:
        '200':
          description: List of Disabilities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Disability'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /places/search:
    get:
      summary: Returns a list of places whose name matches que queried text.
      tags:
        - Place
      parameters:
        - name: query
          in: query
          schema:
            type: string
          required: true
          allowEmptyValue: false
          description: The text that will be searched
        - name: location
          in: query
          schema:
            type: string
          required: false
          allowEmptyValue: false
          description: 'The latitude and longitude in the format of: lat,lng'
        - name: radius
          in: query
          schema:
            type: integer
            format: int32
          required: false
          allowEmptyValue: true
          description: The radius distance from the location. If present, places in this radius will have priority.
      responses:
        '200':
          description: List of places
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Place'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /places/{id}:
    get:
      summary: Returns info of the specified place.
      tags:
        - Place
      responses:
        '200':
          description: Place info.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceDetails'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
        status:
          type: integer
          format: int32
    Disability:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/DisabilityItem'
    DisabilityItem:
      type: object
      properties:
        id:
          type: integer
          format: int 32
        name:
          type: string
    Place:
      type: object
      properties:
        formatted_address:
          type: string
        geometry:
          type: object
          properties:
            location:
              type: object
              properties:
                lat:
                  type: string
                lng:
                  type: string
        id:
          type: string
        name:
          type: string
        opening_hours:
          type: object
          properties:
            open_now:
              type: boolean
        photos:
          type: array
          items:
            type: object
            properties:
              height:
                type: integer
                format: int32
              html_attributions:
                type: array
                items:
                  type: string
              photo_reference:
                type: string
              width:
                type: integer
                format: int32
        place_id:
          type: string
        rating:
          type: number
          format: float
        types:
          type: array
          items:
            type: string
        totalAccessibilityReviews:
          type: integer
          format: int32
        positiveOpinionsPercentage:
          type: number
          format: float
    PlaceDetails:
      type: object
      properties:
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/Review'
    Review:
      description: A review of a specific place.
      type: object
      properties:
        id:
          type: integer
          format: int32
        user_id:
          type: string
        place_id:
          type: string
        is_accessible:
          $ref: '#/components/schemas/AccessibilityRank'  
        createdAt:
          type: string
          format: timestamp
        updatedAt:
          type: string
          format: timestamp
        highlights:
          description: The points mentioned by the reviewer as highlights for this place
          type: array
          items:
            $ref: '#/components/schemas/DisabilityItem'
    AccessibilityRank:
      type: string
      enum:
        - NO
        - PARTIALLY
        - YES